#!/bin/bash

cd "${0%/*}"

source params.sh

printf "1Return	$CHAN_ROOT	$SERVER_HOST	$SERVER_PORT\r\n"
printf "i	fake	(NULL)	0\r\n"
printf "iArchived threads:	fake	(NULL)	0\r\n"

for thread in $(ls -td [0-9]* 2>/dev/null)
do
	stamp="${thread%_*}"
	no="${thread#*_}"

	cd $thread

	if [[ -e archive ]]
	then
		printf "1[thread] %s (%s)	$CHAN_ROOT/$thread	$SERVER_HOST	$SERVER_PORT\r\n" "$(cat gophertag)" $(date @$stamp +"$DATE_FORMAT")
	fi

	cd ..
done
