#!/bin/sh

cd $(dirname "$0")

. ./params.sh

phitem 1 Return "$CHAN_ROOT"
phline

threads=$(ls -td [0-9]* 2>/dev/null)

if [ $(echo -n $threads | wc -l) -eq 0 ]
then
	phinfo 'There are no archived threads.'
else
	phinfo 'Archived threads:'
fi

for thread in $threads
do
	cd $thread

	stamp=$(cat stamp)

	if [ -e archive ]
	then
		phitem 1 "[thread] $(cat gophertag) $(date -d @$stamp +"$DATE_FORMAT")" "$CHAN_ROOT/$thread"
	fi

	cd ..
done
