#!/bin/sh

arg="$@"

cd $(dirname "$0")

. ./params.sh

if [ -e motd ]
then
	cat motd | phmenu
	phline
fi

stickies=$(ls -td sticky_* 2>/dev/null)

for sticky in $stickies
do
	phitem 1 "[sticky] $(cat $sticky/gophertag)" "$CHAN_ROOT/$sticky"
done

if [ $(echo -n $stickies | grep -c .) -gt 0 ]
then
	phline
fi

if [ "$MAX_THREADS" -gt 0 ]
then
	phitem 7 'New thread (enter title for thread)' "$CHAN_ROOT/newthread"
	phline
fi

cat threadcache 2>/dev/null

if [ "$ENABLE_ARCHIVE" = y ]
then
	phline
	phitem 1 Archive "$CHAN_ROOT/archive"
fi
