#!/bin/bash
saveifs="$IFS"
IFS=''
cat $1 | while read -r line
do
	if [[ "$line" != "#*" ]]
	then
		if echo "$line" | grep -q "	"
		then
			printf "$line\r\n"
		else
			printf "i$line\tfake\t(NULL)\t0\r\n"
		fi
	fi
done
IFS="$saveifs"
