#!/bin/bash

cd "${0%/*}"

thread=$(basename $(pwd))
thread="${thread#sticky_*}"

if [ ! -e "../params.sh" ]
then
	exit
fi

source ../params.sh

if [[ -e archive ]]
then
	printf "1Return	$CHAN_ROOT/archive	$SERVER_HOST	$SERVER_PORT\r\n"
else
	printf "1Return	$CHAN_ROOT	$SERVER_HOST	$SERVER_PORT\r\n"
fi

printf "i	fake	(NULL)	0\r\n"

printf "i$(date -d @$thread +"$DATE_FORMAT")"

if [[ -e archive ]]
then
	archivedate=$(cat archive)
	printf " (archived $(date -d @$archivedate +"$DATE_FORMAT"))"
fi
printf "	fake	(NULL)	0\r\n"

../gophermaputil <<EOF

___________________________________________________________________
$(cat gophertag)
___________________________________________________________________

EOF

i=1

for file in $(ls [0-9]* 2>/dev/null)
do
	printf "i__[#%.3d $(date -d @$file +"$DATE_FORMAT") @$file]_______________________\tfake\t(NULL)\t0\r\n" "$i"
	comment=$(cat $file)
	if echo "$comment" | grep -q "	"
	then
		printf "$comment\r\n"
	else
		comment=$(echo "$comment" | fmt -67)
		while read line
		do
			printf "i$line\tfake\t(NULL)\t0\r\n"
		done < <(echo "$comment")
	fi
	printf "i\tfake\t(NULL)\t0\r\n"
	i=$((i+1))
done
