#!/bin/bash

cd "${0%/*}"

thread=$(basename $(pwd))
thread="${thread#sticky_*}"

if [ ! -e "../../params.sh" ]
then
	exit
fi

source ../../params.sh

../../gophermaputil <<EOF
1Return	$CHAN_ROOT/$CHAN_ARCHIVE	$SERVER_HOST	$SERVER_PORT

$(date -d @$thread +"$DATE_FORMAT")
___________________________________________________________________
$(cat gophertag)
___________________________________________________________________

EOF

i=1

for file in $(ls [0-9]* 2>/dev/null)
do
	printf "i__[#%.3d $(date -d @$file +"$DATE_FORMAT") @$file]_______________________\t(fake)\tNULL\t0\r\n" "$i"
	comment=$(cat $file)
	if echo "$comment" | grep -q "	"
	then
		printf "$comment\r\n"
	else
		comment=$(echo "$comment" | fmt -67)
		while read line
		do
			printf "i$line\t(fake)\tNULL\t0\r\n"
		done < <(echo "$comment")
	fi
	printf "i\t(fake)\tNULL\t0\r\n"
	i=$((i+1))
done
