#!/bin/sh

cd $(dirname "$0")

if ! test -e ../params.sh
then
	exit
fi

. ../params.sh

id=$(basename $(pwd))

if test "$MAX_POSTS" -gt 0 -a $(ls [0-9]* 2>/dev/null | wc -l) -ge $MAX_POSTS
then
	pherror "Post failed"
	phline
	phinfo "Post limit reached."
	phitem 1 "Return to thread" "$CHAN_ROOT/$id"
	exit 1
fi

comment=$(echo "$@" | base64 -d)
len=$(echo -n "$comment" | wc -c)

stamp=$(date +%s)

if test -e ../posts
then
	no=$(cat ../posts)
else
	no=0
fi
no=$(($no + 1))

post="$stamp"_"$no"

if test "$comment" = ""
then
	pherror "Post failed"
	phline
	phinfo "You must post a comment."
	phitem 1 "Return to thread" "$CHAN_ROOT/$id"
	exit 1
fi

if test "$len" -gt "$MAX_POSTLEN"
then
	pherror "Post failed"
	phline
	phinfo "Comment too long"
	phitem 1 "Return to thread" "$CHAN_ROOT/$id"
	exit 1
fi

if ! sh ../cooldown.sh post
then
	pherror "Post failed"
	phline
	phinfo "Please wait $POST_LIMIT seconds before posting again."
	phitem 1 "Return to thread" "$CHAN_ROOT/$id"
	exit 1
fi

# post id
if test "$ENABLE_POST_IDS" = y
then
	postid=$(sh ../tripcode.sh "$SALT_DIR" "$REMOTE_HOST")
	echo "${no} ${postid}" >> ../postids
fi

# tripcode
TRIPCODE_REGEX='^##([^ ]+) (.*)$'
if echo "$comment" | grep -Eq "$TRIPCODE_REGEX"
then
	password=$(echo "$comment" | sed -r "s/${TRIPCODE_REGEX}/\1/")
	tripcode=$(sh ../tripcode.sh "$SALT_DIR" "$password")
	comment=$(echo "$comment" | sed -r "s/${TRIPCODE_REGEX}/\2/")
	echo "${no} ${tripcode}" >> ../tripcodes
fi

# quotes
if echo "$comment" | grep -Eq '^>>[0-9]+ ?.*$'
then
	targetno=$(echo "$comment" | sed -r 's/>>([0-9]+) ?.*/\1/')
	target=$(find .. -name "[0-9]*_$targetno" | head -n 1)

	if [ ! -e "$target" ]
	then
		pherror "Post #$targetno does not exist."
		phitem 1 'Return to thread' "$CHAN_ROOT/$id"
		exit 1
	fi

	thread=$(echo "$target" | cut -d / -f 2)

	if [ "$thread" = "$id" ]
	then
		echo "#$targetno said:" >> $post
	else
		echo "1#$targetno said:	$CHAN_ROOT/$thread	$SERVER_HOST	$SERVER_PORT" >> $post
	fi

	saveifs="$IFS"
	IFS=''
	cat $target | while read -r line
	do
		if echo "$line" | grep -v -q "	"
		then
			echo "$line" | fmt -66 -s | fold -w 66 | while read -r fmtline
			do
				echo "  >$fmtline" >> $post
			done
		else
			kind=$(echo "$line" | head -c 1)
			rest=$(echo "$line" | tail -c +2)
			echo "$kind  >$rest" >> $post
		fi
	done
	IFS="$saveifs"

	comment=$(echo "$comment" | sed -r 's/>>[0-9]+ ?(.*)/\1/' | sed 's/	/    /g')
fi

echo "$comment" >> $post

if [ -e $post ]
then
	phinfo "Post successful!"

	echo $no > ../posts

	sh ../addpostpass.sh $no

	sh ../updatepostcache.sh $id $post >> postcache

	cd ..
	sh updatethreadcache.sh > threadcache

	if [ "$MAX_RSS_ITEMS" -gt 0 ]
	then
		sh updaterss.sh $id $no "$comment"
	fi
else
	pherror "Could not post."
fi

phitem 1 "Return to thread" "$CHAN_ROOT/$id"
