#!/bin/bash

cd "${0%/*}"

if [ ! -e "../params.sh" ]
then
	exit 1
fi

source ../params.sh

id=$(basename $(pwd))

stamp=$(date +%s)

if [[ -e ../posts ]]
then
	no=$(cat ../posts)
else
	no=0
fi
no=$(($no + 1))

post="$stamp"_"$no"

url=$(echo "$@" | cut -c1-$MAX_POSTLEN)

if [[ "$url" != *"://"* ]]
then
	printf "3Invalid URL: $url	fake	(NULL)	0\r\n"
	printf "iYou must include the protocol (http://, gopher://, etc.)	fake	(NULL)	0\r\n"
	printf "1Return to thread	$CHAN_ROOT/$id	$SERVER_HOST	$SERVER_PORT\r\n"
	exit 1
fi

proto="${url%://*}"
uri="${url##*://}"

if [[ "$proto" == *" "* ]]
then
	display=$(echo "$proto" | rev | cut -f 2- -d ' ' | rev | cut -c1-69)
	proto=$(echo "$proto" | rev | cut -f 1 -d ' ' | rev)
else
	display=$(echo "$url" | cut -c1-69)
fi

# quotes
targetno=$(echo "$display" | sed -r 's/>>([0-9]+) ?.*/\1/')
if  [[ "$display" == ">>"* && "$targetno" -gt 0 ]]
then
	target=$(ls ../[0-9]*_*/[0-9]*_$targetno 2>/dev/null | head -n 1)
	target="${target#../}"

	if [[ ! "$target" ]]
	then
		printf "3Post #$targetno does not exist!	fake	(NULL)	0\r\n"
		printf "1Return to thread	$CHAN_ROOT/$id	$SERVER_HOST	$SERVER_PORT\r\n"
		exit 1
	fi

	thread="${target%/*}"

	if [[ "$thread" == "$id" ]]
	then
		echo "#$targetno said:" >> $post
	else
		echo "1$targetno said:	$CHAN_ROOT/$thread	$SERVER_HOST	$SERVER_PORT" >> $post
	fi

	saveifs="$IFS"
	IFS=''
	while read line
	do
		if echo "$line" | grep -q -v "	"
		then
			while read fmtline
			do
				echo "  >$fmtline" >> $post
			done < <(echo "$line" | fmt -66 -s | fold -w 66)
		else
			kind=$(echo "$line" | head -c 1)
			rest=$(echo "$line" | tail -c +2)
			echo "$kind  >$rest" >> $post
		fi
	done < ../$target
	IFS="$saveifs"

	display=$(echo "$display" | sed -r 's/>>[0-9]+ ?(.*)/\1/')

	if [[ ! "$display" ]]
	then
		display="$proto://$uri"
	fi
fi

case $proto in
	"")		printf "3Invalid URL: $url	fake	(NULL)	0\r\n"
			printf "1Return to thread	$CHAN_ROOT/$id	$SERVER_HOST	$SERVER_PORT\r\n"
			exit 1;;
	"gopher")	comment=$(../guri "$proto://$uri" "$display");;
	*)		comment="h$display	URL:$proto://$uri	$SERVER_HOST	$SERVER_PORT"
esac

if [[ ! "$comment" ]]
then
	printf "3Post failed.	fake	(NULL)	0\r\n"
	printf "iInvalid URL:	fake	(NULL)	0\r\n"
	printf "i$url	fake	(NULL)	0\r\n"
else
	echo "$comment" >> $post

	if [ -e $post ]
	then
		printf "iPost successfuly!	fake	(NULL)	0\r\n"

		echo $no > ../posts
	else
		printf "3Could not post.	fake	(NULL)	0\r\n"
	fi
fi

printf "1Return to thread	$CHAN_ROOT/$id	$SERVER_HOST	$SERVER_PORT\r\n"
