#!/bin/bash

cd "${0%/*}"

if [ ! "$@" ]
then
	exit
fi

if [ ! -e ../params.sh ]
then
	exit
fi

source ../params.sh

if [ ! $MAX_UPLOAD -gt 0 ]
then
	printf "3Uploads are disabled	fake	(NULL)	0\r\n"
	printf "1Return to thread	$CHAN_ROOT/$id	$SERVER_HOST	$SERVER_PORT\r\n"
	exit
fi

id=$(basename $(pwd))

post=$(date +%s)

ext="$1"
ext="${ext#*://}"
ext="${ext##*/}"
ext="${ext%%\?*}"
ext="${ext##*.}"

url="$1"

uri="${url#*://}"
res="${uri##*/}"
res="${res%%\?*}"
ext="${res##*.}"

if [[ "$ext" == "$res" ]]
then
	ext=""
fi

dis="${@:2}"

if [ ! "$dis" ]
then
	dis=$(echo "$url" | cut -c1-70)
fi

size=$(curl -L -sI "$url" | grep "Content-Length" | awk '{print $2}' | tr -d '\r')

if [ ! "$size" ]
then
	size=0
fi

if [ $size -gt $MAX_UPLOAD ]
then
	printf "3File too large ($size/$MAX_UPLOAD bytes)	fake	(NULL)	0\r\n"
else
	cd ..

	if [[ ! "$ext" ]]
	then
		fname="file_$post"
	else
		fname="file_$post.$ext"
	fi

	curl -L "$url" > "$fname" -m 3 --limit-rate $MAX_UPLOAD

	size=$(stat --printf "%s" "$fname")

	if [ ! "$size" ]
	then
		size=0
	fi

	if [[ $size -gt $MAX_UPLOAD || $? -ne 0 ]]
	then
		printf "3Failed to fetch file (too large or timed out).	fake	(NULL)	0\r\n"
		rm -f "$fname"
	else
		mime=$(file -i -b "$fname")
		mime="${mime%;*}"

		if [[ "$MAX_IMAGE" && "$mime" == "image/"* ]]
		then
			maxw=$(echo $MAX_IMAGE | cut -f 1 -d 'x')
			maxh=$(echo $MAX_IMAGE | cut -f 2 -d 'x')
			dims=$(identify "$fname" | head -n 1 | cut -f 3 -d ' ')
			imgw=$(echo $dims | cut -f 1 -d 'x')
			imgh=$(echo $dims | cut -f 2 -d 'x')

			if [[ $imgw -gt $maxw || $imgh -gt $maxh ]]
			then
				printf "3Image too large ($imgw x $imgh, max $maxw x $maxh)	fake	(NULL)	0\r\n"
				printf "1Return to thread	$CHAN_ROOT/$id	$SERVER_HOST	$SERVER_PORT\r\n"
				rm -f "$fname"
				exit
			fi
		fi

		case "$mime" in
			"image/png")	type=p;;
			"image/jpeg")	type=I;;
			"image/gif")	type=g;;
			"audio/wav")	type=s;;
			"text/html")	type=h;;
			"text/"*)	type=0;;
			*) type=9;;
		esac

		if [[ ! "$ext" ]]
		then
			case "$mime" in
				"video/webm")	ext="webm";;
				"image/png")	ext="png";;
				"image/jpeg")	ext="jpg";;
				"text/html")	ext="html";;
				"text/x-c")	ext="c";;
				*)		ext=""
			esac
			
			if [[ "$ext" != "" ]]
			then
				mv "$fname" "$fname.$ext"
				fname="$fname.$ext"
			fi
		fi

		mv "$fname" $id/

		cd $id

		printf "$type$dis	$CHAN_ROOT/$id/$fname	$SERVER_HOST	$SERVER_PORT\r\n" > $post

		if [ -e $post ]
		then
			printf "iPost successful!	fake	(NULL)	0\r\n"
		else
			printf "3Could not post.	fake	(NULL)	0\r\n"
		fi
	fi
fi

printf "1Return to thread	$CHAN_ROOT/$id	$SERVER_HOST	$SERVER_PORT\r\n"
