#!/bin/bash

cd "${0%/*}"

if [ ! -e "../params.sh" ]
then
	exit 1
fi

source ../params.sh

id=$(basename $(pwd))

comment="$@"
len=${#comment}

stamp=$(date +%s)

if [[ -e ../posts ]]
then
	no=$(cat ../posts)
else
	no=0
fi
no=$(($no + 1))

post="$stamp"_"$no"

if [[ "$comment" = "" ]]
then
	printf "3Post failed.	fake	(NULL)	0\r\n"
	printf "i	fake	(NULL)	0\r\n"
	printf "iYou must post a comment.	fake	(NULL)	0\r\n"
	printf "1Return to thread	$CHAN_ROOT/$id	$SERVER_HOST	$SERVER_PORT\r\n"
	exit 1
fi

if [[ $len -gt $MAX_POSTLEN ]]
then
	printf "3Post failed.	fake	(NULL)	0\r\n"
	printf "i	fake	(NULL)	0\r\n"
	printf "iComment too long ($len/$MAX_POSTLEN)	fake	(NULL)	0\r\n"
	printf "1Return to thread	$CHAN_ROOT/$id	$SERVER_HOST	$SERVER_PORT\r\n"
	exit 1
fi

# quotes
targetno=$(echo "$comment" | sed -r 's/>>([0-9]+) ?.*/\1/')
if [[ "$comment" == ">>"* && "$targetno" -gt 0 ]]
then
	target=$(ls ../[0-9]*/[0-9]*_$targetno 2>/dev/null | head -n 1)
	target="${target#../}"

	if [[ ! "$target" ]]
	then
		printf "3Post #$targetno does not exist.	fake	(NULL)	0\r\n"
		printf "1Return to thread	$CHAN_ROOT/$id	$SERVER_HOST	$SERVER_PORT\r\n"
		exit 1
	fi

	thread="${target%/*}"

	if [[ "$thread" == "$id" ]]
	then
		echo "#$targetno said:" >> $post
	else
		echo "1#$targetno said:	$CHAN_ROOT/$thread	$SERVER_HOST	$SERVER_PORT" >> $post
	fi

	saveifs="$IFS"
	IFS=''
	while read line
	do
		if echo "$line" | grep -v -q "	"
		then
			while read fmtline
			do
				echo "  >$fmtline" >> $post
			done < <(echo "$line" | fmt -69 -s | fold -w 69)
		else
			kind=$(echo "$line" | head -c 1)
			rest=$(echo "$line" | tail -c +2)
			echo "$kind  >$rest" >> $post
		fi
	done < ../$target
	IFS="$saveifs"
	
	comment=$(echo "$comment" | sed -r 's/>>[0-9]+ ?(.*)/\1/')
fi

echo "$comment" > ../s_$post

echo "0*SPOILER*	$CHAN_ROOT/$id/s_$post	$SERVER_HOST	$SERVER_PORT" >> $post

if [ -e $post ]
then
	printf "iPost successful!	fake	(NULL)	0\r\n"

	mv ../s_$post ./

	echo $no > ../posts
else
	printf "3Could not post.	fake	(NULL)	0\r\n"

	rm ../s_$post
fi

printf "1Return to thread	$CHAN_ROOT/$id	$SERVER_HOST	$SERVER_PORT\r\n"
