#!/bin/sh

cd $(dirname "$0")

id=$(basename $(pwd))

if [ ! -e ../params.sh ]
then
	exit 1
fi

. ../params.sh

if [ "$MAX_POSTS" -gt 0 ] && [ $(ls [0-9]* 2>/dev/null | wc -l) -ge "$MAX_POSTS" ]
then
	pherror "Post failed: Post limit reached ($MAX_POSTS)"
	phitem 1 'Return to thread' "$CHAN_ROOT/$id"
	exit 1
fi

stamp=$(date +%s)

if [ -e ../posts ]
then
	no=$(cat ../posts)
else
	no=0
fi
no=$(($no + 1))

post="$stamp"_"$no"

url=$(echo "$@" | cut -c1-$MAX_POSTLEN)

if ! echo "$url" | grep -q '://'
then
	pherror "Invalid URL: $url"
	phinfo 'You must include the protocol (http://, gopher://, etc.)'
	phitem 1 'Return to thread' "$CHAN_ROOT/$id"
	exit 1
fi

proto=$(echo "$url" | sed -r 's/^([^:]+):\/\/.+$/\1/')
uri=$(echo "$url" | sed -r 's/^[^:]+:\/\/(.+)$/\1/')

if echo "$proto" | grep -q ' '
then
	dis=$(echo "$proto" | rev | cut -f 2- -d ' ' | rev | cut -c1-70)
	proto=$(echo "$proto" | rev | cut -f 1 -d ' ' | rev)
else
	dis=$(echo "$url" | cut -c1-70)
fi

# quotes
if echo "$dis" | grep -Eq '^>>[0-9]+ ?.*$'
then
	targetno=$(echo "$dis" | sed -r 's/>>([0-9]+) ?.*/\1/')
	target=$(find .. -name "[0-9]*_$targetno" | head -n 1)

	if [ ! -e "$target" ]
	then
		pherror "Post #$targetno does not exist."
		phitem 1 'Return to thread' "$CHAN_ROOT/$id"
		exit 1
	fi

	thread=$(echo "$target" | cut -d / -f 2)

	if [ "$thread" = "$id" ]
	then
		echo "#$targetno said:" >> $post
	else
		echo "1#$targetno said:	$CHAN_ROOT/$thread	$SERVER_HOST	$SERVER_PORT" >> $post
	fi

	saveifs="$IFS"
	IFS=''
	cat $target | while read -r line
	do
		if echo "$line" | grep -v -q "	"
		then
			echo "$line" | fmt -66 -s | fold -w 66 | while read -r fmtline
			do
				echo "  >$fmtline" >> $post
			done
		else
			kind=$(echo "$line" | head -c 1)
			rest=$(echo "$line" | tail -c +2)
			echo "$kind  >$rest" >> $post
		fi
	done
	IFS="$saveifs"

	dis=$(echo "$dis" | sed -r 's/>>[0-9]+ ?(.*)/\1/' | sed 's/	/    /g')
fi

if [ "$dis" = '' ]
then
	dis="$proto://$uri"
fi

case $proto in
	"")		pherror "Invalid URL: $url"
			phitem 1 'Return to thread'
			exit 1;;
	"gopher")	comment=$(../guri "$proto://$uri" "$dis");;
	*)		comment="h$dis	URL:$proto://$uri	$SERVER_HOST	$SERVER_PORT"
esac

if [ ! "$comment" ]
then
	pherror "Post failed: Invalid URL: $url"
	phitem 1 'Return to thread' "$CHAN_ROOT/$id"
	exit 1
fi

echo "$comment" >> $post

if [ -e $post ]
then
	printf "iPost successfuly!	fake	(NULL)	0\r\n"

	echo $no > ../posts

	sh ../updatepostcache.sh $id $post >> postcache

	cd ..
	sh updatethreadcache.sh > threadcache
else
	printf "3Could not post.	fake	(NULL)	0\r\n"
	pherror 'Could not post'
fi

phitem 1 'Return to thread' "$CHAN_ROOT/$id"
