#!/bin/sh

cd $(dirname "$0")

thread=$(echo $(basename $(pwd)) | sed 's/sticky_//g')

threadstamp=$(cat stamp)

if [ ! -e ../params.sh ]
then
	exit 1
fi

. ../params.sh

if [ -e archive ]
then
	phitem 1 'Return' "$CHAN_ROOT/archive"
else
	phitem 1 'Return' "$CHAN_ROOT"
fi

phline

printf "i##$thread $(date -d @$threadstamp +"$DATE_FORMAT")"

if [ -e archive ]
then
	archivedate=$(cat archive)
	printf " (archived $(date -d @$archivedate +"$DATE_FORMAT"))"
fi

printf "	fake	(NULL)	0\r\n"

phmenu <<EOF
_____________________________________________________________________
$(cat gophertag)
_____________________________________________________________________

EOF

i=1

pad=$(printf %70s | tr ' ' '_')

for file in $(ls [0-9]* 2>/dev/null)
do
	stamp=$(echo "$file" | cut -d _ -f 1)
	no=$(echo "$file" | cut -d _ -f 2)
	posted=$(date -d @$stamp +"$DATE_FORMAT")

	header=$(printf "__[%s #%d]%s" "$posted" $no "$pad" | cut -c1-70)

	phinfo "$header"

	cat "$file" | while read -r line
	do
		if echo "$line" | grep -q "	"
		then
			printf "$line\r\n"
		else
			echo "$line" | fmt -70 | fold -w 70 | while read -r fmtline
			do
				phinfo "$fmtline"
			done
		fi
	done

	phline

	i=$((i+1))
done
