#!/bin/bash

cd "${0%/*}"

thread=$(basename $(pwd))
thread="${thread#sticky_*}"

threadstamp="${thread%_*}"
threadno="${thread#*_}"

if [ ! -e "../params.sh" ]
then
	exit
fi

source ../params.sh

if [[ -e archive ]]
then
	printf "1Return	$CHAN_ROOT/archive	$SERVER_HOST	$SERVER_PORT\r\n"
else
	printf "1Return	$CHAN_ROOT	$SERVER_HOST	$SERVER_PORT\r\n"
fi

printf "i	fake	(NULL)	0\r\n"

printf "i$(date -d @$threadstamp +"$DATE_FORMAT")"

if [[ -e archive ]]
then
	archivedate=$(cat archive)
	printf " (archived $(date -d @$archivedate +"$DATE_FORMAT"))"
fi
printf "	fake	(NULL)	0\r\n"

../gophermaputil <<EOF

_____________________________________________________________________
[##$threadno] $(cat gophertag)
_____________________________________________________________________

EOF

i=1

for file in $(ls [0-9]* 2>/dev/null)
do
	stamp="${file%_*}"
	no="${file#*_}"
	posted=$(date -d @$stamp +"$DATE_FORMAT")

	header=$(printf "__[%s #%d]_______________________________________________" "$posted" $no | cut -c1-69)

	printf "i$header	fake	(NULL)	0\r\n"

	while read line
	do
		if echo "$line" | grep -q "	"
		then
			printf "$line\r\n"
		else
			while read fmtline
			do
				printf "i%s	fake	(NULL)	0\r\n" "$fmtline"
			done < <(echo "$line" | fmt -69)
		fi
	done < $file

	printf "i\tfake\t(NULL)\t0\r\n"

	i=$((i+1))
done
