#!/bin/bash

cd "${0%/*}"

if [[ ! "$@" ]]
then
	exit
fi

if [[ ! -e "../params.sh" ]]
then
	exit
fi

source ../params.sh

id=$(basename $(pwd))

query="$@"

disp="${query%'##'*}"
if [[ "$disp" == "$query" ]]
then
	disp="${query%'#'*}"

	if [[ "$disp" == "$query" ]]
	then
		printf "3No post number (#...) or thread number (##...) specified.	fake	(NULL)	0\r\n"
		printf "1Return to thread	$CHAN_ROOT/$id	$SERVER_HOST	$SERVER_PORT\r\n"
		exit
	else
		link="${query##*#}"
		linktype=post
	fi
else
	link="${query##*'##'}"
	linktype=thread
fi

if [[ ! "$disp" ]]
then
	printf "3You must post a comment.	fake	(NULL)	0\r\n"
	printf "1Return to thread	$CHAN_ROOT/$id	$SERVER_HOST	$SERVER_PORT\r\n"
	exit
fi

case $linktype in
	thread)	target=$(ls -d ../[0-9]*_$link 2>/dev/null | head -n 1);;
	post)	target=$(ls ../[0-9]*/[0-9]*_$link 2>/dev/null | head -n 1);;
esac

if [[ ! "$target" ]]
then
	printf "3"
	case $linktype in
		thread) printf "Thread ##$link ";;
		post)	printf "Post #$link ";;
	esac
	printf "does not exist.	fake	(NULL)	0\r\n"
	printf "1Return to thread	$CHAN_ROOT/$id	$SERVER_HOST	$SERVER_PORT\r\n"
	exit
fi

target="${target#'../'}"

stamp=$(date +%s)

if [[ -e ../posts ]]
then
	no=$(cat ../posts)
else
	no=0
fi
no=$(($no + 1))

post="$stamp"_"$no"

case $linktype in
	thread) echo "1[##${target##*_}] $(cat ../$target/gophertag)	$CHAN_ROOT/$target	$SERVER_HOST	$SERVER_PORT" > $post;;
	post)	thread="${target%/*}"
		if [[ "$thread" != "$id" ]]
		then
			echo "1#${target##*_} said:	$CHAN_ROOT/$thread	$SERVER_HOST	$SERVER_PORT" > ../$post
		else
			echo "#${target##*_} said:" > ../$post
		fi
		saveifs="$IFS"
		IFS=''
		while read line
		do
			if echo "$line" | grep -v -q "	"
			then
				while read fmtline
				do
					echo "  >$fmtline" >> ../$post
				done < <(echo "$line" | fmt -68 -s)
			else
				kind=$(echo "$line" | head -c 1)
				rest=$(echo "$line" | tail -c +2)
				echo "$kind  >$rest" >> ../$post
			fi
		done < ../$target
		IFS="$saveifs"
esac

name=$(basename "$0")

case $name in
	quotepost)	CHAN_POST=$post ./post $disp;;
	quotepostlink)	CHAN_POST=$post ./postlink $disp;;
	quotepostfile)	CHAN_POST=$post ./postfile $disp;;
	quotepostsplr)	CHAN_POST=$post ./postsplr $disp;;
esac

if [[ $? -ne 0 ]]
then
	rm ../$post
	exit $?
fi

mv ../$post ./

if [[ -e $post ]]
then
	printf "iPost successful!	fake	(NULL)	0\r\n"

	echo $no > ../posts
else
	printf "3Could not post.	fake	(NULL)	0\r\n"
fi

printf "1Return to thread	$CHAN_ROOT/$id	$SERVER_HOST	$SERVER_PORT\r\n"
