#!/bin/bash

cd "${0%/*}"

if [ ! -e "../params.sh" ]
then
	exit
fi

source ../params.sh

id=$(basename $(pwd))

post=$(date +%s)

uri=$(echo "$@" | cut -c1-$MAX_POSTLEN)
display=$(echo "$uri" | cut -c1-70)

comment=$(../guri "$uri" "$display")

if [[ ! "$comment" ]]
then
	printf "3Post failed.	fake	(NULL)	0\r\n"
	printf "i	fake	(NULL)	0\r\n"
	printf "iInvalid Gopher URI.	fake	(NULL)	0\r\n"
	printf "i$uri	fake	(NULL)	0\r\n"
else
	echo "$comment" > $post

	if [ -e $post ]
	then
		printf "iPost successful!	fake	(NULL)	0\r\n"
	else
		printf "3Could not post.	fake	(NULL)	0\r\n"
	fi
fi

printf "1Return to thread	$CHAN_ROOT/$id	$SERVER_HOST	$SERVER_PORT\r\n"
