#!/bin/sh

cd $(dirname "$0")

if [ ! -e ../params.sh ]
then
	exit
fi

. ../params.sh

comment="$@"
len=$(echo "$comment" | wc -c)

id=$(basename $(pwd))

stamp=$(date +%s)

if [ "$MAX_POSTS" -gt 0 ] && [ $(find -name '[0-9]*' | wc -l) -ge "$MAX_POSTS" ]
then
	pherror 'Post failed.'
	phinfo "Post limit reached ($MAX_POSTS)"
	phitem 1 'Return to thread' "$CHAN_ROOT/$id"
fi

if [ -e ../posts ]
then
	no=$(cat ../posts)
else
	no=0
fi
no=$((no + 1))

post="$stamp"_"$no"

if [ "$comment" = "" ]
then
	pherror 'Post failed.'
	phline
	phinfo 'You must post a comment.'
	phitem 1 'Return to thread' "$CHAN_ROOT/$id"
	exit 1
fi

if [ "$len" -gt "$MAX_POSTLEN" ]
then
	pherror 'Post failed'
	phline
	phinfo "Comment too long ($len/$MAX_POSTLEN)"
	phitem 1 'Return to thread' "$CHAN_ROOT/$id"
	exit 1
fi

# quotes
targetno=$(echo "$comment" | sed -r 's/>>([0-9]+) ?.*/\1/')
if echo "$comment" | grep -q '^>>.*'
then
	target=$(find .. -name "[0-9]*_$targetno" | head -n 1)

	if [ ! -e "$target" ]
	then
		pherror "Post #$targetno does not exist."
		phitem 1 'Return to thread' "$CHAN_ROOT/$id"
		exit 1
	fi

	thread=$(echo "$target" | cut -d / -f 2)

	if [ "$thread" = "$id" ]
	then
		echo "#$targetno said:" >> $post
	else
		echo "1#$targetno said:	$CHAN_ROOT/$thread	$SERVER_HOST	$SERVER_PORT" >> $post
	fi

	saveifs="$IFS"
	IFS=''
	cat $target | while read -r line
	do
		if echo "$line" | grep -v -q "	"
		then
			echo "$line" | fmt -66 -s | fold -w 66 | while read -r fmtline
			do
				echo "  >$fmtline" >> $post
			done
		else
			kind=$(echo "$line" | head -c 1)
			rest=$(echo "$line" | tail -c +2)
			echo "$kind  >$rest" >> $post
		fi
	done
	IFS="$saveifs"

	comment=$(echo "$comment" | sed -r 's/>>[0-9]+ ?(.*)/\1/' | sed 's/	/    /g')
fi

echo "$comment" >> $post

if [ -e $post ]
then
	phinfo 'Post successful!'

	echo $no > ../posts
	../updatepostcache $id $post >> postcache
else
	pherror 'Could not post.'
fi

phitem 1 'Return to thread' "$CHAN_ROOT/$id"
