#!/bin/bash

cd "${0%/*}"

thread=$(basename $(pwd))
thread="${thread#sticky_*}"

if [[ ! -e "../params.sh" ]]
then
	exit
fi

source ../params.sh

../gophermaputil <<EOF
1Return	$CHAN_ROOT	$SERVER_HOST	$SERVER_PORT

$(date -d @$thread +"$DATE_FORMAT")
_____________________________________________________________________
$(cat gophertag)
_____________________________________________________________________

EOF

if [[ $(ls [0-9]* 2>/dev/null | wc -l) -eq 0 ]]
then
	../gophermaputil <<EOF
This is a new thread. Create an opening post using Reply.

EOF
	if [[ "$SHOW_EMPTY_THREADS" != "y" ]]
	then
		../gophermaputil <<EOF
New threads will not appear on the main menu until they have an
opening post!

EOF
	fi
fi

i=1

for file in $(ls [0-9]* 2>/dev/null)
do
	posted=$(date -d @$file +"$DATE_FORMAT")

	#no=1
	#for post in $(ls -tr ../*/[0-9]* 2>/dev/null)
	#do
	#	if [[ "$(basename $post)" == "$file" ]]
	#	then
	#		break
	#	else
	#		no=$(($no + 1))
	#	fi
	#done

	header=$(printf "__[#%.3d %s @%s]__________________________________________" $i "$posted" $file | cut -c1-69)
	printf "i$header	fake	(NULL)	0\r\n"

	while read line
	do
		if echo "$line" | grep -q "	"
		then
			printf "$line\r\n"
		else
			while read fmtline
			do
				printf "i%s	fake	(NULL)	0\r\n" "$fmtline"
			done < <(echo "$line" | fmt -69)
		fi
	done < $file

	printf "i	fake	(NULL)	0\r\n"

	i=$((i+1))
done

../gophermaputil <<EOF
7Reply	$REQUEST/post	$SERVER_HOST	$SERVER_PORT

7Reply with link	$REQUEST/postlink	$SERVER_HOST	$SERVER_PORT
EOF

if [ $MAX_UPLOAD -gt 0 ]
then
	printf "7Upload image/file from URL (max $(($MAX_UPLOAD / 1000)) kB)	$REQUEST/postfile	$SERVER_HOST	$SERVER_PORT\r\n"
fi

printf "7Reply with spoiler	$REQUEST/postsplr	$SERVER_HOST	$SERVER_PORT\r\n"
