#!/bin/sh

cd $(dirname "$0")

if [ ! -e ../params.sh ]
then
	exit 1
fi

. ../params.sh

if [ "$MAX_POSTS" -gt 0 ] && [ $(ls [0-9]* 2>/dev/null | wc -l) -ge "$MAX_POSTS" ]
then
	pherror 'Post failed: Post limit reached'
	phitem 1 'Return to thread' "$CHAN_ROOT/$id"
	exit 1
fi

id=$(basename $(pwd))

comment="$@"
len=$(echo -n "$comment" | wc -c)

stamp=$(date +%s)

if [ -e ../posts ]
then
	no=$(cat ../posts)
else
	no=0
fi
no=$(($no + 1))

post="$stamp"_"$no"

if [ "$comment" = '' ]
then
	pherror 'Post failed: You must post a comment.'
	phitem 1 'Return to thread' "$CHAN_ROOT/$id"
	exit 1
fi

if [ $len -gt $MAX_POSTLEN ]
then
	pherror "Post failed: Comment too long ($len/$MAX_POSTLEN)"
	phitem 1 'Return to thread' "$CHAN_ROOT/$id"
	exit 1
fi

# quotes
if echo "$comment" | grep -Eq '^>>[0-9]+ ?.*$'
then
	targetno=$(echo "$comment" | sed -r 's/>>([0-9]+) ?.*/\1/')
	target=$(find .. -name "[0-9]*_$targetno" | head -n 1)

	if [ ! -e "$target" ]
	then
		pherror "Post #$targetno does not exist."
		phitem 1 'Return to thread' "$CHAN_ROOT/$id"
		exit 1
	fi

	thread=$(echo "$target" | cut -d / -f 2)

	if [ "$thread" = "$id" ]
	then
		echo "#$targetno said:" >> $post
	else
		echo "1#$targetno said:	$CHAN_ROOT/$thread	$SERVER_HOST	$SERVER_PORT" >> $post
	fi

	saveifs="$IFS"
	IFS=''
	cat $target | while read -r line
	do
		if echo "$line" | grep -v -q "	"
		then
			echo "$line" | fmt -66 -s | fold -w 66 | while read -r fmtline
			do
				echo "  >$fmtline" >> $post
			done
		else
			kind=$(echo "$line" | head -c 1)
			rest=$(echo "$line" | tail -c +2)
			echo "$kind  >$rest" >> $post
		fi
	done
	IFS="$saveifs"

	comment=$(echo "$comment" | sed -r 's/>>[0-9]+ ?(.*)/\1/' | sed 's/	/    /g')
fi

echo "$comment" > ../s_$post

echo "0*SPOILER*	$CHAN_ROOT/$id/s_$post	$SERVER_HOST	$SERVER_PORT" >> $post

if [ -e $post ]
then
	phinfo 'Post successful!'
	mv ../s_$post ./
	echo $no > ../posts

	sh ../addpostpass.sh $no

	sh ../updatepostcache.sh $id $post >> postcache

	cd ..
	sh updatethreadcache.sh > threadcache

	if [ "$MAX_RSS_ITEMS" -gt 0 ]
	then
		sh updaterss.sh $id $no "*SPOILER*"
	fi
else
	pherror 'Could not post.'
	rm ../s_$post
fi

phitem 1 'Return to thread' "$CHAN_ROOT/$id"
