#!/bin/bash

if [[ ! -e "../params.sh" ]]
then
	exit 1
fi

source ../params.sh

pad=$(printf "_%.0s" {1..70})

if [[ "$1" ]]
then
	posts=$(ls "$1" 2>/dev/null)
else
	posts=$(ls -v [0-9]* 2>/dev/null)
fi

for file in $posts
do
	stamp="${file%_*}"
	no="${file#*_}"
	posted=$(date -d @$stamp +"$DATE_FORMAT")

	header=$(printf "__[%s #%d]%s" "$posted" $no "$pad" | cut -c1-69)
	printf "i$header	fake	(NULL)	0\r\n"

	saveifs="$IFS"
	IFS=''
	while read -r line
	do
		if echo "$line" | grep -q "	"
		then
			printf "$line\r\n"
		else
			while read -r fmtline
			do
				printf "i%s	fake	(NULL)	0\r\n" "$fmtline"
			done < <(echo "$line" | fmt -69 | fold -w 69)
		fi
	done < $file
	IFS="$saveifs"

	printf "i	fake	(NULL)	0\r\n"
done
