#!/bin/bash

cd "${0%/*}"

source ../params.sh

../gophermaputil <<EOF
1Return	$CHAN_ROOT	$SERVER_HOST	$SERVER_PORT

Archived threads:
EOF

for thread in $(ls -rd [0-9]* 2>/dev/null)
do
	printf "1[@$thread] $(cat $thread/gophertag)\t$CHAN_ROOT/$CHAN_ARCHIVE/$thread\t$SERVER_HOST\t$SERVER_PORT\r\n"
done
